[project]
name = "creator-lift"
version = "0.0.1"
requires-python = "~=3.14.0"
dependencies = [
    "django",
    "djangorestframework",
    "django-cors-headers",
    "python-dotenv",
    "requests",
    "djangorestframework-simplejwt",
    "psycopg2-binary>=2.9.12",
    "pyjwt>=2.13.0",
    "google-genai>=2.12.1",
    "redis>=8.0.1",
    "django-redis>=7.0.0",
    "boto3>=1.43.70",
    "channels>=4.3.2",
    "channels-redis>=4.3.0",
    "confluent-kafka>=2.15.1",
    "uvicorn[standard]>=0.53.0",
    "gunicorn>=26.2.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
