# Generated by Django 6.0.5 on 2026-07-15 15:39

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfferTags',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('speciality_name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'speciality',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='customusersdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='creatorapp.deals')),
            ],
            options={
                'db_table': 'conversations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_size', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='creatorapp.conversations')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('new_proposal', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('deal_started', 'Deal Started'), ('deal_completed', 'Deal Completed'), ('new_message', 'New Message'), ('new_offer', 'New Offer')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('tiktok_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('youtube_url', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usersdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='creatorapp.profiles')),
            ],
            options={
                'db_table': 'offers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='deals',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deals', to='creatorapp.profiles'),
        ),
        migrations.CreateModel(
            name='CreatorsWorks',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='creatorapp.profiles')),
            ],
            options={
                'db_table': 'creators_works',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='conversations',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='creatorapp.profiles'),
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('delivery_days', models.IntegerField()),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='creatorapp.profiles')),
            ],
            options={
                'db_table': 'proposals',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='deals',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='deal', to='creatorapp.proposals'),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proposals',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='creatorapp.requests'),
        ),
        migrations.AddField(
            model_name='deals',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deals', to='creatorapp.requests'),
        ),
        migrations.CreateModel(
            name='OfferTagJoin',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='creatorapp.offers')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='creatorapp.offertags')),
            ],
            options={
                'db_table': 'offer_tag_join',
                'managed': True,
                'unique_together': {('offer', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='CreatorsWorkTags',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='creatorapp.creatorsworks')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='creatorapp.offertags')),
            ],
            options={
                'db_table': 'creators_work_tags',
                'managed': True,
                'unique_together': {('creator_work', 'tag')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='proposals',
            unique_together={('request', 'creator')},
        ),
        migrations.CreateModel(
            name='RequestTags',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='creatorapp.requests')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='creatorapp.offertags')),
            ],
            options={
                'db_table': 'request_tags',
                'managed': True,
                'unique_together': {('request', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ProfileSpeciality',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='creatorapp.profiles')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='creatorapp.speciality')),
            ],
            options={
                'db_table': 'profile_speciality',
                'managed': True,
                'unique_together': {('profile', 'speciality')},
            },
        ),
    ]
