# Generated by Django 6.0.1 on 2026-03-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusersdata',
            name='username',
        ),
    ]
