# Generated by Django 6.0.5 on 2026-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0002_contactus_offertags_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusersdata',
            name='is_active',
        ),
    ]
