# Generated by Django 6.0.1 on 2026-03-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0002_remove_customusersdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusersdata',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand')], default='creator', max_length=10),
        ),
        migrations.AddField(
            model_name='customusersdata',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
