# Generated by Django 6.0.5 on 2026-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0003_remove_customusersdata_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
