# Generated by Django 6.0.5 on 2026-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0004_offers_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='content_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('photography', 'Photography'), ('tutorial', 'Tutorial'), ('social', 'Social'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
