# Generated by Django 6.0.5 on 2026-09-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0006_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='creatorapp.deals'),
        ),
        migrations.AddConstraint(
            model_name='conversations',
            constraint=models.UniqueConstraint(fields=('brand', 'creator'), name='one_chat_per_brand_creator'),
        ),
    ]
