# Generated by Django 6.0.5 on 2026-10-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0007_alter_conversations_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='creatorapp.proposals'),
        ),
    ]
