# Generated by Django 6.0.5 on 2026-10-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorapp', '0008_conversations_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='creatorapp.conversations'),
        ),
    ]
