"""
Django settings for creatorProject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)tw%ur03khb&(lnvkh$mjfydgw@z)mnds#o*r3$1w+*o#^*#=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'creatorapp.apps.CreatorappConfig',
    'rest_framework_simplejwt.token_blacklist'
]

GOOGLE_CLIENT_ID= os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_SECRET= os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT=os.getenv('GOOGLE_REDIRECT_URL')
SECRET_KEY=os.getenv('SECRET_KEY')
GEMINI_API_KEY=os.getenv('GEMINI_API_KEY')
GEMINI_MODEL=os.getenv('GEMINI_MODEL')
MINIO_ENDPOINT=os.getenv('MINIO_ENDPOINT')
MINIO_ACCESS_KEY=os.getenv('MINIO_USER')
MINIO_SECRET_ACCESS_KEY=os.getenv('MINIO_PASSWORD')
MINIO_BUCKET= os.getenv('MINIO_BUCKET')
MINIO_PUBLIC_URL = os.getenv('MINIO_PUBLIC_URL')
TURNSTILE_SECRET_KEY=os.getenv('TURNSTILE_SECRET_KEY')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',#It inspects incoming HTTP requests and adds the necessary CORS headers to responses
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Your Django app
#     ↓ cache.set("history:user_42", data)
    
# KEY_PREFIX stamps it → "default:history:user_42"
# BACKEND sends it to  → Redis server at localhost:6379
# LOCATION puts it in  → Database /0
# TIMEOUT deletes it   → after 300 seconds automatically
# CLIENT_CLASS handles → opening the actual connection to Redis

# SESSION_ENGINE	Store sessions in cache (Redis), not the database
# SESSION_CACHE_ALIAS	Which named cache to use for sessions
# redis:// vs rediss://	Without SSL vs with SSL (use rediss in production)

CACHES = {
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://127.0.0.1:6379/0",
        "OPTIONS":{
            # this redis client ussed to push oout commands and open connections (intermediary between app and redis server)
            # theres shardclient splits data across multiple redis-servers sentinelclient works for redis clusters
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            'CONNECTION_POOL_KWARGS': {

                'max_connections': 50,          # max 50 open connections at once
                'socket_connect_timeout': 5,    # wait max 5s to open a connection
                'socket_timeout': 5,            # wait max 5s for a command response
                'retry_on_timeout': True,       # on timeout, try once more silently
}
        },
        "KEY_PREFIX":"default",
        "TIMEOUT":300
    },

    "sessions":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://127.0.0.1:6379/1",
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,         
                'socket_connect_timeout': 5,    
                'socket_timeout': 5,            
                'retry_on_timeout': True,       
        }
        },
        "KEY_PREFIX":"sessions",
        "TIMEOUT":86400
    }
} 

SESSION_ENGINE="django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS="sessions"


REST_FRAMEWORK={
    'DEFAULT_PERMISSION_CLASSES':[
         'rest_framework.permissions.IsAuthenticated',  #'rest_framework.permissions.IsAuthenticated'#default-isAuthenticated each route requires a token Allowany-any user can access the data and endpoints without needing a login or API key. 
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'creatorapp.authentication.authentication.JWTAuthentication',#'rest_framework_simplejwt.authentication.JWTAuthentication'-bouncer  #The club looks at the JWT token you bring to prove who you are.It’s like showing a special digital card every time you enter.
    ),

    'EXCEPTION_HANDLER': 'creatorapp.utils.custom_exception_handler',
    # a custom exception handler all error spass through to shape the eroor object 
}

# DjangoModelPermissionsOrAnonReadOnly- get allowed without auth but post put del not
# JWT token = secret club card you carry to prove who you are.
# DRF authentication = the bouncer at the door checking your card.
# Permissions = rules about what people with a valid card can do inside (read, write, etc.).

# Simple JWT → use the library, safe and easy.
# Custom Simple JWT → library does heavy lifting, you add your style. class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
# Fully custom JWT → you do everything, super powerful but risky.

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), #how long its valid
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': True, #give new refresh token after using them to get token
#     'BLACKLIST_AFTER_ROTATION': True, #blacklist old refrehs token
#     'AUTH_HEADER_TYPES': ('Bearer',), #tell it where to look for token
# } only when using simple_jwt

CORS_ORIGIN_ALLOW_ALL= True #permits any website to talk to your API via a browser

CORS_ALLOW_CREDENTIALS = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTH_USER_MODEL = "creatorapp.customUsersData"   #replace the default User model with the customone created
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # React dev server
# ]
ROOT_URLCONF = 'creatorProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'creatorProject.wsgi.application'
ASGI_APPLICATION = 'creatorProject.asgi.application'

CHANNEL_LAYERS= {
    "default":{
        "BACKEND":"channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)]
        }
    }
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':'localhost',
        'PORT':'5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
